### ISSUE TITLE
ConcurrentRequest with too many large data items

### ISSUE THREAD

**Issue by scamille** [mycroes/Sally7#15]
If I use the new concurrent request things with multiple large data items (1000 byte each), I get the following exception:

System.Exception: 'An error was returned during communication:

	Message type: Ack / 0x02
	Error class: ErrorOnSupplies / 0x85
	Error code: 0x0

**Comment by mycroes** [comment]
That error class is funny. I never knew what it was for, but this seems to indicate something like 'Invalid request data'. Anyway, I'm assuming this error is no different than what you would get before? 1000 bytes is too large for 960 bytes PDU, which AFAIK is the largest that's supported by Siemens PLC's (and not even by all).

**Comment by scamille** [comment]
Not sure why yesterday I thought that 1000 bytes would fit, even with a S7 1500 ... Works just fine now with a limit of 500 bytes payload.

I am now using Sally7 0.9.0 and the performance with the ConcurrentRequestExecutor is fantastic :-)
