### ISSUE TITLE
Small cast error in ConvertFromLong

### ISSUE THREAD

**Issue by AndreDrubig** [mycroes/Sally7#19]
I tested you great software and i got errors with writing all long data types. I was looking and i found mistake in ConvertFromLong() in ToS7Conversions.cs line 64 `ConvertFromInt((int) value >> 32, 1, output);`.  Now the cast is done before the shift but it should be fist shift and than cast: `ConvertFromInt((int) (value >> 32), 1, output);`  I came after this by looking at the hexadecimal values in the PLC.

**Comment by mycroes** [comment]
Thanks a lot! Will try to fix this ASAP (busy schedule though, no promises).

**Comment by mycroes** [comment]
Just released v0.10.0, which includes the above fix. Thanks again for reporting!
