### ISSUE TITLE
[Question] How to read different type of  var in a function call

### ISSUE THREAD

**Issue by ypeng-ming** [mycroes/Sally7#56]
Hello,
I have 2 questions
1 We can read multiple same type of vars with code:
`var floatArr = new DataBlockDataItem<float[]> {DbNumber = 9, Length = 4};
await conn.ReadAsync(floatArr);`
Is it possible to read DB1.DBD0(float), DB1.DBW4(short), DB1.DBX6.1(bool) in a function  call?

2. How to write to multiple addresses in a function call? Senario  1: how to write DB1.DBD0, DB1.DBD4 in a function call. Senario 2: how to write DB1.DBD0, DB1.DBX4.1 in a function call?

Thanks!

**Comment by mycroes** [comment]
Hi @ypeng-ming,

You can read multiple items by creating a new `IDataItem[]` with the desired items you want to read. The same applies to writing, just set the `Value` property of the `DataBlockDataItem` to the desired value. You should be able to devise this information from the method signatures as well.

**Comment by ypeng-ming** [comment]
> Hi @ypeng-ming,
> 
> You can read multiple items by creating a new `IDataItem[]` with the desired items you want to read. The same applies to writing, just set the `Value` property of the `DataBlockDataItem` to the desired value. You should be able to devise this information from the method signatures as well.

Thanks for your answer!
